/*******************************************************************************
 * ListSelectorUI.java
 * =============================================================================
 * Copyright (c) 2009-2010 Australian Antarctic Division. All rights reserved.
 * Author can be contacted at troy.robertson@aad.gov.au.
 *
 * Every effort has been taken in making sure that the source code is
 * technically accurate, but I disclaim any and all responsibility for any loss,
 * damage or destruction of data or any other property which may arise from
 * relying on it. I will in no case be liable for any monetary damages arising
 * from such loss, damage or destruction.
 *
 * As with any code, ensure this code is tested in a development environment
 * before attempting to run it in production.
 * =============================================================================
 */
package au.gov.aad.erm.EPOC_Builder;

import javax.swing.*;
import java.util.*;

/*******************************************************************************
 * GUI for list selection.
 *
 * @author Troy Robertson
 * @company Australian Antarctic Division
 * @created 10/09/2009
 * @version 0.4.0, 01-09-2010
 ******************************************************************************/
public class ListSelectorUI extends javax.swing.JPanel {
    private DefaultListModel selectionList;

    public ListSelectorUI(String txt, ArrayList lst) {
        this(txt, lst, null);
    }

    /**
     * Creates new form ListSelectorUI
     * @param txt title for list
     * @param lst ArrayList containing arrays of length 2, first element being
     *              uid and second display name
     * @param selected selected object
     */
    public ListSelectorUI(String txt, ArrayList lst, Object selected) {
        initComponents();
        int selIdx = 0;

        jLabelText.setText(txt);
        
        selectionList = new DefaultListModel();
        for (int i=0; i < lst.size(); i++) {
            if (lst.get(i) instanceof EPOCObject) {
                selectionList.addElement(lst.get(i));
                jListSelection.setCellRenderer(new EPOCObjectListRenderer());
                if (selected != null && lst.get(i) == selected) selIdx = i;
            } else {
                // otherwise expect an array containing uid/displayname
                selectionList.addElement(((String[])lst.get(i))[1]);
            }
        }
        jListSelection.setModel(selectionList);
        //if (selected != null)
            jListSelection.setSelectedIndex(selIdx);
        jListSelection.ensureIndexIsVisible(selIdx);
    }
    
    public int getSelectionIndex() {
        return jListSelection.getSelectedIndex();
    }
    
    public Object getSelectionObject() {
        return jListSelection.getSelectedValue();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSelection = new javax.swing.JList();
        jLabelText = new javax.swing.JLabel();

        jListSelection.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListSelection);

        jLabelText.setText("{open text}");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabelText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabelText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelText;
    private javax.swing.JList jListSelection;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
