/*******************************************************************************
 * OptionsUI.java
 * =============================================================================
 * Copyright (c) 2009-2010 Australian Antarctic Division. All rights reserved.
 * Author can be contacted at troy.robertson@aad.gov.au.
 *
 * Every effort has been taken in making sure that the source code is
 * technically accurate, but I disclaim any and all responsibility for any loss,
 * damage or destruction of data or any other property which may arise from
 * relying on it. I will in no case be liable for any monetary damages arising
 * from such loss, damage or destruction.
 *
 * As with any code, ensure this code is tested in a development environment
 * before attempting to run it in production.
 * =============================================================================
 */
package au.gov.aad.erm.EPOC_Builder;

import static au.gov.aad.erm.EPOC_Builder.Constants.*;

/*******************************************************************************
 * Settings/Options GUI.
 *
 * @author Troy Robertson
 * @company Australian Antarctic Division
 * @created 11/03/2010
 * @version 0.4.0, 01-09-2010
 ******************************************************************************/
public class OptionsUI extends OpposingPanelUI {

    /** Creates new form OptionsUI */
    public OptionsUI() {
        initComponents();
        loadForm();
    }

    private void loadForm() {
        jTextVersion.setText(EPOC_VER);
        jTextSchemaVersion.setText(EPOC_DBVER);
        jTextElementStr.setText(EPOC_ELESTR);
        jCheckDebug.setSelected(EPOC_DBG);
        jCheckTemplateEdit.setSelected(EPOC_EDIT_TEMPL);
        jCheckTemplateLinked.setSelected(EPOC_TMPL_LINK_OBJ);
        jCheckImportLinked.setSelected(EPOC_IMP_LINK_OBJ);
        jCheckMatchTemplates.setSelected(EPOC_AUTO_MATCH_MEMBERS);
        jCheckAutoMatchLinked.setSelected(EPOC_AUTO_MATCH_LINK_OBJ);
        if (!EPOC_AUTO_MATCH_LINK_OBJ) {
            jCheckAutoMatchLinkedTempl.setSelected(false);
        } else {
            jCheckAutoMatchLinkedTempl.setSelected(EPOC_AUTO_MATCH_LINK_TEMPL_OBJ);
        }
    }

    /*
     * Set editability of form
     */
    public void editable(boolean editable) {
        // Element tab
        jTextVersion.setEditable(false);
        jTextSchemaVersion.setEditable(false);
        jTextElementStr.setEditable(editable);
        jCheckDebug.setEnabled(editable);
        jCheckTemplateEdit.setEnabled(editable);
        jCheckTemplateLinked.setEnabled(editable);
        jCheckImportLinked.setEnabled(editable);
        jCheckMatchTemplates.setEnabled(editable);
        jCheckAutoMatchLinked.setEnabled(editable);
        if (!EPOC_AUTO_MATCH_LINK_OBJ) {
            jLabelInclude.setEnabled(false);
            jCheckAutoMatchLinkedTempl.setEnabled(false);
        } else {
            jLabelInclude.setEnabled(editable);
            jCheckAutoMatchLinkedTempl.setEnabled(editable);
        }
    }

    public int saveIfModified() {
        // Check if form data has been modified, if so update object
        if (isModified()) {
            EPOC_DBVER = jTextSchemaVersion.getText();
            EPOC_ELESTR = jTextElementStr.getText();
            EPOC_DBG = jCheckDebug.isSelected();
            EPOC_EDIT_TEMPL = jCheckTemplateEdit.isSelected();
            EPOC_TMPL_LINK_OBJ = jCheckTemplateLinked.isSelected();
            EPOC_IMP_LINK_OBJ = jCheckImportLinked.isSelected();
            EPOC_AUTO_MATCH_MEMBERS = jCheckMatchTemplates.isSelected();
            EPOC_AUTO_MATCH_LINK_OBJ = jCheckAutoMatchLinked.isSelected();
            EPOC_AUTO_MATCH_LINK_TEMPL_OBJ = jCheckAutoMatchLinkedTempl.isSelected();

            return EPOC_SUCC;
        }

        return EPOC_NONE;
    }

    /**
     * Have form values been modified when compared to stored object data
     * @return boolean
     */
    public boolean isModified() {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextVersion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextElementStr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckDebug = new javax.swing.JCheckBox();
        jCheckMatchTemplates = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckTemplateLinked = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextSchemaVersion = new javax.swing.JTextField();
        jCheckTemplateEdit = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckImportLinked = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckAutoMatchLinked = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabelInclude = new javax.swing.JLabel();
        jCheckAutoMatchLinkedTempl = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextVersion.setEditable(false);

        jLabel1.setText("EPOC Builder version:");

        jLabel2.setText("R code Element dummy string:");

        jLabel3.setText("Debug mode:");

        jLabel4.setText("Match comparable templates on XML import/save as:");

        jLabel5.setText("Template down through linked objects:");

        jLabel6.setText("Database schema version:");

        jTextSchemaVersion.setEditable(false);

        jLabel7.setText("Allow template editing without revision:");

        jLabel8.setText("Import down through linked objects:");

        jCheckAutoMatchLinked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAutoMatchLinkedActionPerformed(evt);
            }
        });

        jLabel9.setText("Auto-match broken linked objects to local members:");

        jLabelInclude.setText("- include matching to external template objects:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tools.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(428, Short.MAX_VALUE)
                .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel6)
                    .add(jLabel2)
                    .add(jLabel8)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel7)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jLabelInclude)
                        .add(jLabel9))
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckTemplateEdit)
                            .add(jCheckTemplateLinked)
                            .add(jCheckImportLinked)
                            .add(jCheckAutoMatchLinked)
                            .add(jCheckAutoMatchLinkedTempl)
                            .add(jCheckMatchTemplates)
                            .add(jCheckDebug)))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jTextElementStr)
                        .add(jTextSchemaVersion)
                        .add(jTextVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(12, 12, 12)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel2))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jTextVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextSchemaVersion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextElementStr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(9, 9, 9)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckDebug)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jCheckTemplateEdit))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jCheckTemplateLinked))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jCheckImportLinked)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckMatchTemplates))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelInclude))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jCheckAutoMatchLinked)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckAutoMatchLinkedTempl)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jLabel10)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckAutoMatchLinkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAutoMatchLinkedActionPerformed
        if (jCheckAutoMatchLinked.isSelected()) {
            jLabelInclude.setEnabled(true);
            jCheckAutoMatchLinkedTempl.setEnabled(true);
        } else {
            jCheckAutoMatchLinkedTempl.setSelected(false);
            jLabelInclude.setEnabled(false);
            jCheckAutoMatchLinkedTempl.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckAutoMatchLinkedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckAutoMatchLinked;
    private javax.swing.JCheckBox jCheckAutoMatchLinkedTempl;
    private javax.swing.JCheckBox jCheckDebug;
    private javax.swing.JCheckBox jCheckImportLinked;
    private javax.swing.JCheckBox jCheckMatchTemplates;
    private javax.swing.JCheckBox jCheckTemplateEdit;
    private javax.swing.JCheckBox jCheckTemplateLinked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInclude;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextElementStr;
    private javax.swing.JTextField jTextSchemaVersion;
    private javax.swing.JTextField jTextVersion;
    // End of variables declaration//GEN-END:variables

}
